info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T02:52:19.274Z"}
info: Connected to the database. {"timestamp":"2022-01-28T02:52:19.344Z"}
error: 
    status - 500 
    message - Error: Book not found
    at _callee8$ (D:\Book_Store_App\Book-Store\src\services\/user.service.js:170:11)
    at tryCatch (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) 
    url - /api/v1/books/61f174f2ce436f2844f6173d 
    method - GET 
    IP - ::1
   {"timestamp":"2022-01-28T03:00:46.667Z"}
error: 
    status - 500 
    message - Error: User Acess Denied
    at _callee$ (D:\Book_Store_App\Book-Store\src\middlewares\/auth.middleware.js:30:14)
    at tryCatch (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>) 
    url - /api/v1/books/61f1763bf950f0116082e712 
    method - DELETE 
    IP - ::1
   {"timestamp":"2022-01-28T03:03:03.184Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T03:04:16.389Z"}
info: Connected to the database. {"timestamp":"2022-01-28T03:04:16.443Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T13:48:19.155Z"}
error: Could not connect to the database. connect ECONNREFUSED 127.0.0.1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"Error: \n    at new MongooseError (D:\\Book_Store_App\\Book-Store\\node_modules\\mongoose\\lib\\error\\mongooseError.js:7:1)\n    at new MongooseServerSelectionError (D:\\Book_Store_App\\Book-Store\\node_modules\\mongoose\\lib\\error\\serverSelection.js:26:1)\n    at NativeConnection.Connection.openUri (D:\\Book_Store_App\\Book-Store\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at D:\\Book_Store_App\\Book-Store\\node_modules\\mongoose\\lib\\index.js:351:10\n    at D:\\Book_Store_App\\Book-Store\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (D:\\Book_Store_App\\Book-Store\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (D:\\Book_Store_App\\Book-Store\\node_modules\\mongoose\\lib\\index.js:1149:10)","timestamp":"2022-01-28T13:48:49.114Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T15:02:39.715Z"}
error: Could not connect to the database. connect ECONNREFUSED 127.0.0.1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"Error: \n    at new MongooseError (D:\\Book_Store_App\\Book-Store\\node_modules\\mongoose\\lib\\error\\mongooseError.js:7:1)\n    at new MongooseServerSelectionError (D:\\Book_Store_App\\Book-Store\\node_modules\\mongoose\\lib\\error\\serverSelection.js:26:1)\n    at NativeConnection.Connection.openUri (D:\\Book_Store_App\\Book-Store\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at D:\\Book_Store_App\\Book-Store\\node_modules\\mongoose\\lib\\index.js:351:10\n    at D:\\Book_Store_App\\Book-Store\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (D:\\Book_Store_App\\Book-Store\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (D:\\Book_Store_App\\Book-Store\\node_modules\\mongoose\\lib\\index.js:1149:10)","timestamp":"2022-01-28T15:03:09.733Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T15:05:23.012Z"}
error: Could not connect to the database. connect ECONNREFUSED 127.0.0.1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"Error: \n    at new MongooseError (D:\\Book_Store_App\\Book-Store\\node_modules\\mongoose\\lib\\error\\mongooseError.js:7:1)\n    at new MongooseServerSelectionError (D:\\Book_Store_App\\Book-Store\\node_modules\\mongoose\\lib\\error\\serverSelection.js:26:1)\n    at NativeConnection.Connection.openUri (D:\\Book_Store_App\\Book-Store\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at D:\\Book_Store_App\\Book-Store\\node_modules\\mongoose\\lib\\index.js:351:10\n    at D:\\Book_Store_App\\Book-Store\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (D:\\Book_Store_App\\Book-Store\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (D:\\Book_Store_App\\Book-Store\\node_modules\\mongoose\\lib\\index.js:1149:10)","timestamp":"2022-01-28T15:05:53.028Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T15:17:51.408Z"}
info: Connected to the database. {"timestamp":"2022-01-28T15:17:51.498Z"}
error: 
    status - 500 
    message - Error: User does not exist
    at _callee$ (D:\Book_Store_App\Book-Store\src\middlewares\/checkuser.middleware.js:14:12)
    at tryCatch (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) 
    url - /api/v1/users/user_login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-28T15:18:25.805Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T15:19:05.399Z"}
info: Connected to the database. {"timestamp":"2022-01-28T15:19:05.472Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T15:19:21.013Z"}
info: Connected to the database. {"timestamp":"2022-01-28T15:19:21.099Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T15:23:29.895Z"}
info: Connected to the database. {"timestamp":"2022-01-28T15:23:29.973Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T15:24:39.044Z"}
info: Connected to the database. {"timestamp":"2022-01-28T15:24:39.106Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T15:25:19.794Z"}
info: Connected to the database. {"timestamp":"2022-01-28T15:25:19.861Z"}
error: 
    status - 500 
    message - Error: User Acess Denied
    at _callee$ (D:\Book_Store_App\Book-Store\src\middlewares\/auth.middleware.js:30:14)
    at tryCatch (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>) 
    url - /api/v1/cart/ 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-28T15:38:04.993Z"}
error: 
    status - 500 
    message - Error: User Acess Denied
    at _callee$ (D:\Book_Store_App\Book-Store\src\middlewares\/auth.middleware.js:30:14)
    at tryCatch (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>) 
    url - /api/v1/Cart/ 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-28T15:38:13.759Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T15:40:13.815Z"}
info: Connected to the database. {"timestamp":"2022-01-28T15:40:13.878Z"}
info: Connected to the database. {"timestamp":"2022-01-28T15:40:41.525Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T15:40:59.828Z"}
info: Connected to the database. {"timestamp":"2022-01-28T15:40:59.953Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T15:41:06.466Z"}
info: Connected to the database. {"timestamp":"2022-01-28T15:41:06.548Z"}
error: 
    status - 500 
    message - ReferenceError: body is not defined
    at _callee10$ (D:\Book_Store_App\Book-Store\src\services\/user.service.js:190:30)
    at tryCatch (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.AddCart (D:\Book_Store_App\Book-Store\src\services\/user.service.js:187:21) 
    url - /api/v1/cart/ 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-28T15:41:06.809Z"}
error: 
    status - 500 
    message - ReferenceError: body is not defined
    at _callee10$ (D:\Book_Store_App\Book-Store\src\services\/user.service.js:190:30)
    at tryCatch (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.AddCart (D:\Book_Store_App\Book-Store\src\services\/user.service.js:187:21) 
    url - /api/v1/cart/ 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-28T15:41:50.022Z"}
error: 
    status - 500 
    message - ReferenceError: body is not defined
    at _callee10$ (D:\Book_Store_App\Book-Store\src\services\/user.service.js:190:30)
    at tryCatch (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.AddCart (D:\Book_Store_App\Book-Store\src\services\/user.service.js:187:21) 
    url - /api/v1/cart/ 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-28T15:42:29.610Z"}
error: 
    status - 500 
    message - ReferenceError: body is not defined
    at _callee10$ (D:\Book_Store_App\Book-Store\src\services\/user.service.js:190:30)
    at tryCatch (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.AddCart (D:\Book_Store_App\Book-Store\src\services\/user.service.js:187:21) 
    url - /api/v1/cart/ 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-28T15:42:31.012Z"}
error: 
    status - 500 
    message - ReferenceError: body is not defined
    at _callee10$ (D:\Book_Store_App\Book-Store\src\services\/user.service.js:190:30)
    at tryCatch (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.AddCart (D:\Book_Store_App\Book-Store\src\services\/user.service.js:187:21) 
    url - /api/v1/cart/ 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-28T15:43:19.081Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T15:43:52.355Z"}
info: Connected to the database. {"timestamp":"2022-01-28T15:43:52.429Z"}
error: 
    status - 500 
    message - SyntaxError: Unexpected token " in JSON at position 2
    at JSON.parse (<anonymous>)
    at createStrictSyntaxError (D:\Book_Store_App\Book-Store\node_modules\body-parser\lib\types\json.js:158:10)
    at parse (D:\Book_Store_App\Book-Store\node_modules\body-parser\lib\types\json.js:83:15)
    at D:\Book_Store_App\Book-Store\node_modules\body-parser\lib\read.js:121:18
    at invokeCallback (D:\Book_Store_App\Book-Store\node_modules\raw-body\index.js:224:16)
    at done (D:\Book_Store_App\Book-Store\node_modules\raw-body\index.js:213:7)
    at IncomingMessage.onEnd (D:\Book_Store_App\Book-Store\node_modules\raw-body\index.js:273:7)
    at IncomingMessage.emit (events.js:387:35)
    at IncomingMessage.emit (domain.js:470:12)
    at endReadableNT (internal/streams/readable.js:1317:12) 
    url - /api/v1/cart/ 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-28T15:46:59.574Z"}
error: 
    status - 500 
    message - SyntaxError: Unexpected token " in JSON at position 2
    at JSON.parse (<anonymous>)
    at createStrictSyntaxError (D:\Book_Store_App\Book-Store\node_modules\body-parser\lib\types\json.js:158:10)
    at parse (D:\Book_Store_App\Book-Store\node_modules\body-parser\lib\types\json.js:83:15)
    at D:\Book_Store_App\Book-Store\node_modules\body-parser\lib\read.js:121:18
    at invokeCallback (D:\Book_Store_App\Book-Store\node_modules\raw-body\index.js:224:16)
    at done (D:\Book_Store_App\Book-Store\node_modules\raw-body\index.js:213:7)
    at IncomingMessage.onEnd (D:\Book_Store_App\Book-Store\node_modules\raw-body\index.js:273:7)
    at IncomingMessage.emit (events.js:387:35)
    at IncomingMessage.emit (domain.js:470:12)
    at endReadableNT (internal/streams/readable.js:1317:12) 
    url - /api/v1/cart/ 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-28T15:47:02.638Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T15:48:59.279Z"}
info: Connected to the database. {"timestamp":"2022-01-28T15:48:59.356Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T15:49:38.736Z"}
info: Connected to the database. {"timestamp":"2022-01-28T15:49:38.822Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T15:51:25.374Z"}
info: Connected to the database. {"timestamp":"2022-01-28T15:51:25.472Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T15:51:37.346Z"}
info: Connected to the database. {"timestamp":"2022-01-28T15:51:37.435Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T15:52:32.412Z"}
info: Connected to the database. {"timestamp":"2022-01-28T15:52:32.507Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T15:52:41.487Z"}
info: Connected to the database. {"timestamp":"2022-01-28T15:52:41.563Z"}
error: 
    status - 500 
    message - Error: Cast to undefined failed for value undefined at path "undefined"
    at new MongooseError (D:\Book_Store_App\Book-Store\node_modules\mongoose\lib\error\mongooseError.js:7:1)
    at new CastError (D:\Book_Store_App\Book-Store\node_modules\mongoose\lib\error\cast.js:31:7)
    at model.Query.exec (D:\Book_Store_App\Book-Store\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (D:\Book_Store_App\Book-Store\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) 
    url - /api/v1/cart/ 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-28T15:52:50.075Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T15:53:20.646Z"}
info: Connected to the database. {"timestamp":"2022-01-28T15:53:20.721Z"}
error: 
    status - 500 
    message - ReferenceError: user is not defined
    at _callee10$ (D:\Book_Store_App\Book-Store\src\services\/user.service.js:190:28)
    at tryCatch (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.AddCart (D:\Book_Store_App\Book-Store\src\services\/user.service.js:187:21) 
    url - /api/v1/cart/ 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-28T15:53:20.964Z"}
error: 
    status - 500 
    message - ReferenceError: user is not defined
    at _callee10$ (D:\Book_Store_App\Book-Store\src\services\/user.service.js:190:28)
    at tryCatch (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.AddCart (D:\Book_Store_App\Book-Store\src\services\/user.service.js:187:21) 
    url - /api/v1/cart/ 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-28T15:53:27.251Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T15:53:42.833Z"}
info: Connected to the database. {"timestamp":"2022-01-28T15:53:42.913Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T15:54:13.865Z"}
info: Connected to the database. {"timestamp":"2022-01-28T15:54:13.996Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T15:54:58.847Z"}
info: Connected to the database. {"timestamp":"2022-01-28T15:54:58.979Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T15:55:10.677Z"}
info: Connected to the database. {"timestamp":"2022-01-28T15:55:10.749Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T15:56:02.002Z"}
info: Connected to the database. {"timestamp":"2022-01-28T15:56:02.080Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T15:56:44.725Z"}
info: Connected to the database. {"timestamp":"2022-01-28T15:56:44.829Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T15:57:48.285Z"}
info: Connected to the database. {"timestamp":"2022-01-28T15:57:48.358Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T15:58:00.867Z"}
info: Connected to the database. {"timestamp":"2022-01-28T15:58:00.963Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T15:58:26.850Z"}
info: Connected to the database. {"timestamp":"2022-01-28T15:58:26.925Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T16:00:00.980Z"}
info: Connected to the database. {"timestamp":"2022-01-28T16:00:01.095Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T16:00:16.195Z"}
info: Connected to the database. {"timestamp":"2022-01-28T16:00:16.267Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T16:00:32.945Z"}
info: Connected to the database. {"timestamp":"2022-01-28T16:00:33.127Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T16:02:43.230Z"}
info: Connected to the database. {"timestamp":"2022-01-28T16:02:43.263Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T16:16:38.528Z"}
info: Connected to the database. {"timestamp":"2022-01-28T16:16:38.621Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T16:16:46.027Z"}
info: Connected to the database. {"timestamp":"2022-01-28T16:16:46.146Z"}
error: 
    status - 500 
    message - Error: Cart validation failed
    at new MongooseError (D:\Book_Store_App\Book-Store\node_modules\mongoose\lib\error\mongooseError.js:7:1)
    at new ValidationError (D:\Book_Store_App\Book-Store\node_modules\mongoose\lib\error\validation.js:27:5)
    at model.Document.invalidate (D:\Book_Store_App\Book-Store\node_modules\mongoose\lib\document.js:2782:32)
    at EmbeddedDocument.invalidate (D:\Book_Store_App\Book-Store\node_modules\mongoose\lib\types\embedded.js:298:29)
    at EmbeddedDocument.$set (D:\Book_Store_App\Book-Store\node_modules\mongoose\lib\document.js:1349:12)
    at EmbeddedDocument.$set (D:\Book_Store_App\Book-Store\node_modules\mongoose\lib\document.js:1058:16)
    at EmbeddedDocument.Document (D:\Book_Store_App\Book-Store\node_modules\mongoose\lib\document.js:148:12)
    at EmbeddedDocument [as constructor] (D:\Book_Store_App\Book-Store\node_modules\mongoose\lib\types\embedded.js:47:12) 
    url - /api/v1/cart/ 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-28T16:24:06.715Z"}
error: 
    status - 500 
    message - Error: Cart validation failed
    at new MongooseError (D:\Book_Store_App\Book-Store\node_modules\mongoose\lib\error\mongooseError.js:7:1)
    at new ValidationError (D:\Book_Store_App\Book-Store\node_modules\mongoose\lib\error\validation.js:27:5)
    at model.Document.invalidate (D:\Book_Store_App\Book-Store\node_modules\mongoose\lib\document.js:2782:32)
    at EmbeddedDocument.invalidate (D:\Book_Store_App\Book-Store\node_modules\mongoose\lib\types\embedded.js:298:29)
    at EmbeddedDocument.$set (D:\Book_Store_App\Book-Store\node_modules\mongoose\lib\document.js:1349:12)
    at EmbeddedDocument.$set (D:\Book_Store_App\Book-Store\node_modules\mongoose\lib\document.js:1058:16)
    at EmbeddedDocument.Document (D:\Book_Store_App\Book-Store\node_modules\mongoose\lib\document.js:148:12)
    at EmbeddedDocument [as constructor] (D:\Book_Store_App\Book-Store\node_modules\mongoose\lib\types\embedded.js:47:12) 
    url - /api/v1/cart/ 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-28T16:24:37.633Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T16:25:10.520Z"}
info: Connected to the database. {"timestamp":"2022-01-28T16:25:10.605Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T16:26:35.905Z"}
info: Connected to the database. {"timestamp":"2022-01-28T16:26:35.991Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T16:26:44.925Z"}
info: Connected to the database. {"timestamp":"2022-01-28T16:26:44.995Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T16:27:12.534Z"}
info: Connected to the database. {"timestamp":"2022-01-28T16:27:12.614Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T16:27:34.047Z"}
info: Connected to the database. {"timestamp":"2022-01-28T16:27:34.131Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T16:28:37.425Z"}
info: Connected to the database. {"timestamp":"2022-01-28T16:28:37.521Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T16:53:46.177Z"}
info: Connected to the database. {"timestamp":"2022-01-28T16:53:46.271Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T16:59:54.007Z"}
info: Connected to the database. {"timestamp":"2022-01-28T16:59:54.084Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T17:01:10.768Z"}
info: Connected to the database. {"timestamp":"2022-01-28T17:01:10.873Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T17:02:25.750Z"}
info: Connected to the database. {"timestamp":"2022-01-28T17:02:25.822Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T17:02:48.255Z"}
info: Connected to the database. {"timestamp":"2022-01-28T17:02:48.337Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T17:03:05.868Z"}
info: Connected to the database. {"timestamp":"2022-01-28T17:03:05.970Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T17:03:19.529Z"}
info: Connected to the database. {"timestamp":"2022-01-28T17:03:19.605Z"}
error: 
    status - 500 
    message - ReferenceError: req is not defined
    at _callee10$ (D:\Book_Store_App\Book-Store\src\services\/user.service.js:193:1)
    at tryCatch (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.AddCart (D:\Book_Store_App\Book-Store\src\services\/user.service.js:187:21) 
    url - /api/v1/cart/ 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-28T17:03:19.919Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T17:03:36.952Z"}
info: Connected to the database. {"timestamp":"2022-01-28T17:03:37.017Z"}
error: 
    status - 500 
    message - ReferenceError: req is not defined
    at _callee10$ (D:\Book_Store_App\Book-Store\src\services\/user.service.js:193:1)
    at tryCatch (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.AddCart (D:\Book_Store_App\Book-Store\src\services\/user.service.js:187:21) 
    url - /api/v1/cart/ 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-28T17:03:37.576Z"}
error: 
    status - 500 
    message - ReferenceError: req is not defined
    at _callee10$ (D:\Book_Store_App\Book-Store\src\services\/user.service.js:193:1)
    at tryCatch (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.AddCart (D:\Book_Store_App\Book-Store\src\services\/user.service.js:187:21) 
    url - /api/v1/cart/ 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-28T17:03:38.327Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T17:03:55.877Z"}
info: Connected to the database. {"timestamp":"2022-01-28T17:03:56.033Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T17:04:13.160Z"}
info: Connected to the database. {"timestamp":"2022-01-28T17:04:13.230Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T17:04:32.512Z"}
info: Connected to the database. {"timestamp":"2022-01-28T17:04:32.585Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T17:04:51.464Z"}
info: Connected to the database. {"timestamp":"2022-01-28T17:04:51.493Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T17:05:57.816Z"}
info: Connected to the database. {"timestamp":"2022-01-28T17:05:57.894Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T17:10:44.411Z"}
info: Connected to the database. {"timestamp":"2022-01-28T17:10:44.490Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T17:12:21.768Z"}
info: Connected to the database. {"timestamp":"2022-01-28T17:12:21.890Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T17:12:32.444Z"}
info: Connected to the database. {"timestamp":"2022-01-28T17:12:32.498Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T17:13:08.944Z"}
info: Connected to the database. {"timestamp":"2022-01-28T17:13:09.024Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T17:13:17.204Z"}
info: Connected to the database. {"timestamp":"2022-01-28T17:13:17.277Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T17:13:44.755Z"}
info: Connected to the database. {"timestamp":"2022-01-28T17:13:44.823Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T17:16:00.827Z"}
info: Connected to the database. {"timestamp":"2022-01-28T17:16:00.903Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T17:16:34.816Z"}
info: Connected to the database. {"timestamp":"2022-01-28T17:16:34.844Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T17:16:46.499Z"}
info: Connected to the database. {"timestamp":"2022-01-28T17:16:46.592Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T17:16:53.854Z"}
info: Connected to the database. {"timestamp":"2022-01-28T17:16:53.923Z"}
error: 
    status - 500 
    message - TypeError: data is not a constructor
    at _callee10$ (D:\Book_Store_App\Book-Store\src\services\/user.service.js:197:12)
    at tryCatch (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.AddCart (D:\Book_Store_App\Book-Store\src\services\/user.service.js:187:21) 
    url - /api/v1/cart/ 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-28T17:16:54.469Z"}
error: 
    status - 500 
    message - TypeError: data is not a constructor
    at _callee10$ (D:\Book_Store_App\Book-Store\src\services\/user.service.js:197:12)
    at tryCatch (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.AddCart (D:\Book_Store_App\Book-Store\src\services\/user.service.js:187:21) 
    url - /api/v1/cart/ 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-28T17:16:55.007Z"}
error: 
    status - 500 
    message - TypeError: data is not a constructor
    at _callee10$ (D:\Book_Store_App\Book-Store\src\services\/user.service.js:197:12)
    at tryCatch (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.AddCart (D:\Book_Store_App\Book-Store\src\services\/user.service.js:187:21) 
    url - /api/v1/cart/ 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-28T17:16:55.325Z"}
error: 
    status - 500 
    message - TypeError: data is not a constructor
    at _callee10$ (D:\Book_Store_App\Book-Store\src\services\/user.service.js:197:12)
    at tryCatch (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.AddCart (D:\Book_Store_App\Book-Store\src\services\/user.service.js:187:21) 
    url - /api/v1/cart/ 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-28T17:17:40.190Z"}
error: 
    status - 500 
    message - TypeError: data is not a constructor
    at _callee10$ (D:\Book_Store_App\Book-Store\src\services\/user.service.js:197:12)
    at tryCatch (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.AddCart (D:\Book_Store_App\Book-Store\src\services\/user.service.js:187:21) 
    url - /api/v1/cart/ 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-28T17:17:41.254Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T17:18:36.860Z"}
info: Connected to the database. {"timestamp":"2022-01-28T17:18:36.936Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T17:19:13.816Z"}
info: Connected to the database. {"timestamp":"2022-01-28T17:19:13.910Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T17:21:19.907Z"}
info: Connected to the database. {"timestamp":"2022-01-28T17:21:19.958Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T17:28:55.748Z"}
info: Connected to the database. {"timestamp":"2022-01-28T17:28:55.830Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T17:34:34.025Z"}
info: Connected to the database. {"timestamp":"2022-01-28T17:34:34.058Z"}
error: 
    status - 500 
    message - TypeError: _cart.default.save is not a function
    at _callee10$ (D:\Book_Store_App\Book-Store\src\services\/user.service.js:206:22)
    at tryCatch (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.AddCart (D:\Book_Store_App\Book-Store\src\services\/user.service.js:187:21) 
    url - /api/v1/cart/ 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-28T17:34:40.723Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T17:35:36.814Z"}
info: Connected to the database. {"timestamp":"2022-01-28T17:35:36.901Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T17:35:48.564Z"}
info: Connected to the database. {"timestamp":"2022-01-28T17:35:48.638Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T17:40:01.914Z"}
info: Connected to the database. {"timestamp":"2022-01-28T17:40:02.004Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T17:40:11.951Z"}
info: Connected to the database. {"timestamp":"2022-01-28T17:40:12.023Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T17:40:34.607Z"}
info: Connected to the database. {"timestamp":"2022-01-28T17:40:34.685Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T17:42:03.246Z"}
info: Connected to the database. {"timestamp":"2022-01-28T17:42:03.325Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T17:42:26.695Z"}
info: Connected to the database. {"timestamp":"2022-01-28T17:42:26.917Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T17:44:03.616Z"}
info: Connected to the database. {"timestamp":"2022-01-28T17:44:03.716Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T17:46:39.097Z"}
info: Connected to the database. {"timestamp":"2022-01-28T17:46:39.175Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T17:47:14.710Z"}
info: Connected to the database. {"timestamp":"2022-01-28T17:47:14.788Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T17:47:25.504Z"}
info: Connected to the database. {"timestamp":"2022-01-28T17:47:25.587Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T17:52:59.634Z"}
info: Connected to the database. {"timestamp":"2022-01-28T17:52:59.732Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T17:53:49.108Z"}
info: Connected to the database. {"timestamp":"2022-01-28T17:53:49.183Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T17:54:46.352Z"}
info: Connected to the database. {"timestamp":"2022-01-28T17:54:46.467Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T17:55:13.723Z"}
info: Connected to the database. {"timestamp":"2022-01-28T17:55:13.795Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T17:55:24.247Z"}
info: Connected to the database. {"timestamp":"2022-01-28T17:55:24.337Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T17:55:30.538Z"}
info: Connected to the database. {"timestamp":"2022-01-28T17:55:30.607Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T17:56:24.601Z"}
info: Connected to the database. {"timestamp":"2022-01-28T17:56:24.662Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T17:56:47.469Z"}
info: Connected to the database. {"timestamp":"2022-01-28T17:56:47.539Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T17:57:04.963Z"}
info: Connected to the database. {"timestamp":"2022-01-28T17:57:05.036Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T17:58:05.778Z"}
info: Connected to the database. {"timestamp":"2022-01-28T17:58:05.867Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T17:58:13.735Z"}
info: Connected to the database. {"timestamp":"2022-01-28T17:58:13.803Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T17:59:25.474Z"}
info: Connected to the database. {"timestamp":"2022-01-28T17:59:25.555Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-01-28T17:59:33.073Z"}
info: Connected to the database. {"timestamp":"2022-01-28T17:59:33.098Z"}
error: 
    status - 500 
    message - Error: Cast to undefined failed for value undefined at path "undefined"
    at new MongooseError (D:\Book_Store_App\Book-Store\node_modules\mongoose\lib\error\mongooseError.js:7:1)
    at new CastError (D:\Book_Store_App\Book-Store\node_modules\mongoose\lib\error\cast.js:31:7)
    at model.Query.exec (D:\Book_Store_App\Book-Store\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (D:\Book_Store_App\Book-Store\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) 
    url - /api/v1/cart/ 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-28T18:00:22.708Z"}
error: 
    status - 500 
    message - Error: Book not available
    at _callee10$ (D:\Book_Store_App\Book-Store\src\services\/user.service.js:198:9)
    at tryCatch (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) 
    url - /api/v1/cart/ 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-28T18:18:17.659Z"}
