error: 
    status - 500 
    message - Error: User validation failed
    at new MongooseError (D:\Book_Store_App\Book-Store\node_modules\mongoose\lib\error\mongooseError.js:7:1)
    at new ValidationError (D:\Book_Store_App\Book-Store\node_modules\mongoose\lib\error\validation.js:27:5)
    at model.Document.invalidate (D:\Book_Store_App\Book-Store\node_modules\mongoose\lib\document.js:2782:32)
    at model.$set (D:\Book_Store_App\Book-Store\node_modules\mongoose\lib\document.js:1349:12)
    at model.$set (D:\Book_Store_App\Book-Store\node_modules\mongoose\lib\document.js:1058:16)
    at model.Document (D:\Book_Store_App\Book-Store\node_modules\mongoose\lib\document.js:148:12)
    at model.Model (D:\Book_Store_App\Book-Store\node_modules\mongoose\lib\model.js:106:12)
    at new model (D:\Book_Store_App\Book-Store\node_modules\mongoose\lib\model.js:4911:15) 
    url - /api/v1/users/user_registration 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-24T11:16:18.806Z"}
error: 
      status - 11000
      message - E11000 duplicate key error collection: Book_Store.users index: Email_1 dup key: { Email: "vishgirase@gmail.com" } 
      url - /api/v1/users/user_registration 
      method - POST 
      IP - ::1
     {"timestamp":"2022-01-24T11:17:31.889Z"}
error: 
    status - 500 
    message - RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: 11000
    at ServerResponse.writeHead (_http_server.js:259:11)
    at ServerResponse.writeHead (D:\Book_Store_App\Book-Store\node_modules\on-headers\index.js:44:26)
    at ServerResponse._implicitHeader (_http_server.js:250:8)
    at write_ (_http_outgoing.js:711:9)
    at ServerResponse.end (_http_outgoing.js:825:5)
    at ServerResponse.send (D:\Book_Store_App\Book-Store\node_modules\express\lib\response.js:221:10)
    at ServerResponse.json (D:\Book_Store_App\Book-Store\node_modules\express\lib\response.js:267:15)
    at appErrorHandler (D:\Book_Store_App\Book-Store\src\middlewares\/error.middleware.js:36:26)
    at Layer.handle_error (D:\Book_Store_App\Book-Store\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (D:\Book_Store_App\Book-Store\node_modules\express\lib\router\index.js:321:13) 
    url - /api/v1/users/user_registration 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-24T11:17:31.898Z"}
error: 
      status - 11000
      message - E11000 duplicate key error collection: Book_Store.users index: Email_1 dup key: { Email: "vishgirase@gmail.com" } 
      url - /api/v1/users/user_registration 
      method - POST 
      IP - ::1
     {"timestamp":"2022-01-24T11:17:36.526Z"}
error: 
    status - 500 
    message - RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: 11000
    at ServerResponse.writeHead (_http_server.js:259:11)
    at ServerResponse.writeHead (D:\Book_Store_App\Book-Store\node_modules\on-headers\index.js:44:26)
    at ServerResponse._implicitHeader (_http_server.js:250:8)
    at write_ (_http_outgoing.js:711:9)
    at ServerResponse.end (_http_outgoing.js:825:5)
    at ServerResponse.send (D:\Book_Store_App\Book-Store\node_modules\express\lib\response.js:221:10)
    at ServerResponse.json (D:\Book_Store_App\Book-Store\node_modules\express\lib\response.js:267:15)
    at appErrorHandler (D:\Book_Store_App\Book-Store\src\middlewares\/error.middleware.js:36:26)
    at Layer.handle_error (D:\Book_Store_App\Book-Store\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (D:\Book_Store_App\Book-Store\node_modules\express\lib\router\index.js:321:13) 
    url - /api/v1/users/user_registration 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-24T11:17:36.527Z"}
error: 
    status - 500 
    message - Error: "FirstName" length must be at least 3 characters long
    at new exports.ValidationError (D:\Book_Store_App\Book-Store\node_modules\@hapi\joi\lib\errors.js:246:9)
    at Object.exports.process (D:\Book_Store_App\Book-Store\node_modules\@hapi\joi\lib\errors.js:189:29)
    at Object.internals.entry (D:\Book_Store_App\Book-Store\node_modules\@hapi\joi\lib\validator.js:140:26)
    at Object.exports.entry (D:\Book_Store_App\Book-Store\node_modules\@hapi\joi\lib\validator.js:26:30)
    at internals.Base.validate (D:\Book_Store_App\Book-Store\node_modules\@hapi\joi\lib\base.js:534:26)
    at newUserValidator (D:\Book_Store_App\Book-Store\src\validators\/user.validator.js:11:35)
    at Layer.handle [as handle_request] (D:\Book_Store_App\Book-Store\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Book_Store_App\Book-Store\node_modules\express\lib\router\route.js:137:13) 
    url - /api/v1/users/user_registration 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-24T11:22:19.330Z"}
error: 
    status - 500 
    message - Error: "Email" must be a valid email
    at new exports.ValidationError (D:\Book_Store_App\Book-Store\node_modules\@hapi\joi\lib\errors.js:246:9)
    at Object.exports.process (D:\Book_Store_App\Book-Store\node_modules\@hapi\joi\lib\errors.js:189:29)
    at Object.internals.entry (D:\Book_Store_App\Book-Store\node_modules\@hapi\joi\lib\validator.js:140:26)
    at Object.exports.entry (D:\Book_Store_App\Book-Store\node_modules\@hapi\joi\lib\validator.js:26:30)
    at internals.Base.validate (D:\Book_Store_App\Book-Store\node_modules\@hapi\joi\lib\base.js:534:26)
    at newUserValidator (D:\Book_Store_App\Book-Store\src\validators\/user.validator.js:11:35)
    at Layer.handle [as handle_request] (D:\Book_Store_App\Book-Store\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Book_Store_App\Book-Store\node_modules\express\lib\router\route.js:137:13) 
    url - /api/v1/users/user_registration 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-24T11:24:39.472Z"}
error: 
    status - 500 
    message - Error: "Role" is not allowed
    at new exports.ValidationError (D:\Book_Store_App\Book-Store\node_modules\@hapi\joi\lib\errors.js:246:9)
    at Object.exports.process (D:\Book_Store_App\Book-Store\node_modules\@hapi\joi\lib\errors.js:189:29)
    at Object.internals.entry (D:\Book_Store_App\Book-Store\node_modules\@hapi\joi\lib\validator.js:140:26)
    at Object.exports.entry (D:\Book_Store_App\Book-Store\node_modules\@hapi\joi\lib\validator.js:26:30)
    at internals.Base.validate (D:\Book_Store_App\Book-Store\node_modules\@hapi\joi\lib\base.js:534:26)
    at newUserValidator (D:\Book_Store_App\Book-Store\src\validators\/user.validator.js:11:35)
    at Layer.handle [as handle_request] (D:\Book_Store_App\Book-Store\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Book_Store_App\Book-Store\node_modules\express\lib\router\route.js:137:13) 
    url - /api/v1/users/user_registration 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-24T11:25:07.380Z"}
error: 
      status - 11000
      message - E11000 duplicate key error collection: Book_Store.users index: Email_1 dup key: { Email: "vishgirhhjjdggkkkjjs4@gmail.com" } 
      url - /api/v1/users/admin_registration 
      method - POST 
      IP - ::1
     {"timestamp":"2022-01-24T13:18:08.249Z"}
error: 
    status - 500 
    message - RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: 11000
    at ServerResponse.writeHead (_http_server.js:259:11)
    at ServerResponse.writeHead (D:\Book_Store_App\Book-Store\node_modules\on-headers\index.js:44:26)
    at ServerResponse._implicitHeader (_http_server.js:250:8)
    at write_ (_http_outgoing.js:711:9)
    at ServerResponse.end (_http_outgoing.js:825:5)
    at ServerResponse.send (D:\Book_Store_App\Book-Store\node_modules\express\lib\response.js:221:10)
    at ServerResponse.json (D:\Book_Store_App\Book-Store\node_modules\express\lib\response.js:267:15)
    at appErrorHandler (D:\Book_Store_App\Book-Store\src\middlewares\/error.middleware.js:36:26)
    at Layer.handle_error (D:\Book_Store_App\Book-Store\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (D:\Book_Store_App\Book-Store\node_modules\express\lib\router\index.js:321:13) 
    url - /api/v1/users/admin_registration 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-24T13:18:08.279Z"}
error: 
    status - 500 
    message - Error: User Already Exsist
    at _callee$ (D:\Book_Store_App\Book-Store\src\services\/user.service.js:9:9)
    at tryCatch (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) 
    url - /api/v1/users/admin_registration 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-24T13:21:16.293Z"}
error: 
    status - 500 
    message - Error: User Already Exsist
    at _callee$ (D:\Book_Store_App\Book-Store\src\services\/user.service.js:9:9)
    at tryCatch (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) 
    url - /api/v1/users/user_registration 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-24T13:21:36.385Z"}
error: 
    status - 500 
    message - Error: User Already Exsist
    at _callee$ (D:\Book_Store_App\Book-Store\src\services\/user.service.js:11:11)
    at tryCatch (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) 
    url - /api/v1/users/admin_registration 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-24T13:35:51.426Z"}
error: 
    status - 500 
    message - Error: Mail ID Not Exist
    at _callee2$ (D:\Book_Store_App\Book-Store\src\services\/user.service.js:32:9)
    at tryCatch (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-24T15:41:42.191Z"}
error: 
    status - 500 
    message - Error: Please enter correct Mail Id
    at _callee2$ (D:\Book_Store_App\Book-Store\src\services\/user.service.js:36:9)
    at tryCatch (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-24T15:43:47.928Z"}
error: 
    status - 500 
    message - ReferenceError: Password is not defined
    at _callee2$ (D:\Book_Store_App\Book-Store\src\services\/user.service.js:33:32)
    at tryCatch (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-24T15:52:54.756Z"}
error: 
    status - 500 
    message - ReferenceError: Password is not defined
    at _callee2$ (D:\Book_Store_App\Book-Store\src\services\/user.service.js:33:32)
    at tryCatch (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-24T15:54:10.701Z"}
error: 
    status - 500 
    message - ReferenceError: Password is not defined
    at _callee2$ (D:\Book_Store_App\Book-Store\src\services\/user.service.js:33:32)
    at tryCatch (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-24T15:55:24.404Z"}
error: 
    status - 500 
    message - ReferenceError: Password is not defined
    at _callee2$ (D:\Book_Store_App\Book-Store\src\services\/user.service.js:34:32)
    at tryCatch (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-24T15:56:15.158Z"}
error: 
    status - 500 
    message - ReferenceError: Password is not defined
    at _callee2$ (D:\Book_Store_App\Book-Store\src\services\/user.service.js:34:32)
    at tryCatch (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-24T15:56:21.307Z"}
error: 
    status - 500 
    message - Error: Please enter correct Mail Id
    at _callee2$ (D:\Book_Store_App\Book-Store\src\services\/user.service.js:41:9)
    at tryCatch (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-24T16:03:08.283Z"}
error: 
    status - 500 
    message - Error: Please enter corret mail id or password
    at _callee2$ (D:\Book_Store_App\Book-Store\src\services\/user.service.js:37:10)
    at tryCatch (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-24T16:03:27.043Z"}
error: 
    status - 500 
    message - Error: secretOrPrivateKey must have a value
    at Object.sign (D:\Book_Store_App\Book-Store\node_modules\jsonwebtoken\sign.js:107:20)
    at _callee2$ (D:\Book_Store_App\Book-Store\src\services\/user.service.js:39:19)
    at tryCatch (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-24T16:25:27.268Z"}
error: 
    status - 500 
    message - Error: secretOrPrivateKey must have a value
    at Object.sign (D:\Book_Store_App\Book-Store\node_modules\jsonwebtoken\sign.js:107:20)
    at _callee2$ (D:\Book_Store_App\Book-Store\src\services\/user.service.js:39:19)
    at tryCatch (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-24T16:25:28.352Z"}
error: 
    status - 500 
    message - Error: secretOrPrivateKey must have a value
    at Object.sign (D:\Book_Store_App\Book-Store\node_modules\jsonwebtoken\sign.js:107:20)
    at _callee2$ (D:\Book_Store_App\Book-Store\src\services\/user.service.js:40:19)
    at tryCatch (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-24T16:26:42.646Z"}
error: 
    status - 500 
    message - Error: secretOrPrivateKey must have a value
    at Object.sign (D:\Book_Store_App\Book-Store\node_modules\jsonwebtoken\sign.js:107:20)
    at _callee2$ (D:\Book_Store_App\Book-Store\src\services\/user.service.js:40:19)
    at tryCatch (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-24T16:26:58.715Z"}
error: 
    status - 500 
    message - TypeError: Cannot read property 'Email' of undefined
    at checkuser (D:\Book_Store_App\Book-Store\src\middlewares\/checkuser.middleware.js:5:46)
    at Layer.handle [as handle_request] (D:\Book_Store_App\Book-Store\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Book_Store_App\Book-Store\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (D:\Book_Store_App\Book-Store\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\Book_Store_App\Book-Store\node_modules\express\lib\router\layer.js:95:5)
    at D:\Book_Store_App\Book-Store\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (D:\Book_Store_App\Book-Store\node_modules\express\lib\router\index.js:341:12)
    at next (D:\Book_Store_App\Book-Store\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (D:\Book_Store_App\Book-Store\node_modules\express\lib\router\index.js:174:3)
    at router (D:\Book_Store_App\Book-Store\node_modules\express\lib\router\index.js:47:12) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-25T05:49:13.533Z"}
error: 
    status - 500 
    message - TypeError: Cannot read property 'Email' of undefined
    at checkuser (D:\Book_Store_App\Book-Store\src\middlewares\/checkuser.middleware.js:5:46)
    at Layer.handle [as handle_request] (D:\Book_Store_App\Book-Store\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Book_Store_App\Book-Store\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (D:\Book_Store_App\Book-Store\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\Book_Store_App\Book-Store\node_modules\express\lib\router\layer.js:95:5)
    at D:\Book_Store_App\Book-Store\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (D:\Book_Store_App\Book-Store\node_modules\express\lib\router\index.js:341:12)
    at next (D:\Book_Store_App\Book-Store\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (D:\Book_Store_App\Book-Store\node_modules\express\lib\router\index.js:174:3)
    at router (D:\Book_Store_App\Book-Store\node_modules\express\lib\router\index.js:47:12) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-25T05:49:33.030Z"}
error: 
    status - 500 
    message - TypeError: Cannot read property 'Email' of undefined
    at checkuser (D:\Book_Store_App\Book-Store\src\middlewares\/checkuser.middleware.js:5:46)
    at Layer.handle [as handle_request] (D:\Book_Store_App\Book-Store\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Book_Store_App\Book-Store\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (D:\Book_Store_App\Book-Store\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\Book_Store_App\Book-Store\node_modules\express\lib\router\layer.js:95:5)
    at D:\Book_Store_App\Book-Store\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (D:\Book_Store_App\Book-Store\node_modules\express\lib\router\index.js:341:12)
    at next (D:\Book_Store_App\Book-Store\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (D:\Book_Store_App\Book-Store\node_modules\express\lib\router\index.js:174:3)
    at router (D:\Book_Store_App\Book-Store\node_modules\express\lib\router\index.js:47:12) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-25T05:49:41.108Z"}
error: 
    status - 500 
    message - Error: data and hash arguments required
    at Object.compare (D:\Book_Store_App\Book-Store\node_modules\bcrypt\bcrypt.js:208:17)
    at D:\Book_Store_App\Book-Store\node_modules\bcrypt\promises.js:29:12
    at new Promise (<anonymous>)
    at Object.module.exports.promise (D:\Book_Store_App\Book-Store\node_modules\bcrypt\promises.js:20:12)
    at Object.compare (D:\Book_Store_App\Book-Store\node_modules\bcrypt\bcrypt.js:204:25)
    at _callee2$ (D:\Book_Store_App\Book-Store\src\services\/user.service.js:40:34)
    at tryCatch (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:294:22) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-25T05:52:10.114Z"}
error: 
    status - 500 
    message - Error: Please enter corret mail id or password
    at _callee2$ (D:\Book_Store_App\Book-Store\src\services\/user.service.js:51:13)
    at tryCatch (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-25T05:52:25.539Z"}
error: 
    status - 500 
    message - Error: "FirstName" is required
    at new exports.ValidationError (D:\Book_Store_App\Book-Store\node_modules\@hapi\joi\lib\errors.js:246:9)
    at Object.exports.process (D:\Book_Store_App\Book-Store\node_modules\@hapi\joi\lib\errors.js:189:29)
    at Object.internals.entry (D:\Book_Store_App\Book-Store\node_modules\@hapi\joi\lib\validator.js:140:26)
    at Object.exports.entry (D:\Book_Store_App\Book-Store\node_modules\@hapi\joi\lib\validator.js:26:30)
    at internals.Base.validate (D:\Book_Store_App\Book-Store\node_modules\@hapi\joi\lib\base.js:534:26)
    at newUserValidator (D:\Book_Store_App\Book-Store\src\validators\/user.validator.js:11:35)
    at Layer.handle [as handle_request] (D:\Book_Store_App\Book-Store\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Book_Store_App\Book-Store\node_modules\express\lib\router\route.js:137:13) 
    url - /api/v1/users/user_registration 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-25T05:52:47.244Z"}
error: 
    status - 500 
    message - Error: User Already Exsist
    at _callee$ (D:\Book_Store_App\Book-Store\src\services\/user.service.js:17:11)
    at tryCatch (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) 
    url - /api/v1/users/user_registration 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-25T05:53:23.846Z"}
error: 
    status - 500 
    message - Error: Please enter corret mail id or password
    at _callee2$ (D:\Book_Store_App\Book-Store\src\services\/user.service.js:51:13)
    at tryCatch (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login_user 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-25T06:26:16.996Z"}
error: 
    status - 500 
    message - Error: Please enter corret mail id or password
    at _callee2$ (D:\Book_Store_App\Book-Store\src\services\/user.service.js:51:13)
    at tryCatch (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login_user 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-25T07:52:28.915Z"}
error: 
    status - 500 
    message - Error: Please enter corret mail id or password
    at _callee2$ (D:\Book_Store_App\Book-Store\src\services\/user.service.js:51:13)
    at tryCatch (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login_user 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-25T07:52:50.933Z"}
error: 
    status - 500 
    message - Error: Please enter corret mail id or password
    at _callee2$ (D:\Book_Store_App\Book-Store\src\services\/user.service.js:51:13)
    at tryCatch (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login_user 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-25T07:52:52.817Z"}
error: 
    status - 500 
    message - undefined 
    url - /api/v1/users/login_user 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-25T08:01:30.687Z"}
error: 
    status - 500 
    message - undefined 
    url - /api/v1/users/login_user 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-25T08:01:32.851Z"}
error: 
    status - 500 
    message - undefined 
    url - /api/v1/users/login_admin 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-25T08:08:52.671Z"}
error: 
    status - 500 
    message - undefined 
    url - /api/v1/users/login_admin 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-25T08:19:43.278Z"}
error: 
    status - 500 
    message - undefined 
    url - /api/v1/users/login_user 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-25T08:24:24.983Z"}
error: 
    status - 500 
    message - Error: Please enter correct details
    at _callee2$ (D:\Book_Store_App\Book-Store\src\middlewares\/checkuser.middleware.js:30:6)
    at tryCatch (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) 
    url - /api/v1/users/login_admin 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-25T08:25:00.467Z"}
error: 
    status - 500 
    message - Error: Please enter correct details
    at _callee2$ (D:\Book_Store_App\Book-Store\src\middlewares\/checkuser.middleware.js:30:6)
    at tryCatch (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) 
    url - /api/v1/users/login_admin 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-25T08:41:35.832Z"}
error: 
    status - 500 
    message - Error: Please enter correct details
    at _callee2$ (D:\Book_Store_App\Book-Store\src\middlewares\/checkuser.middleware.js:31:12)
    at tryCatch (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) 
    url - /api/v1/users/login_admin 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-25T08:48:25.751Z"}
error: 
    status - 500 
    message - Error: Please enter correct details
    at _callee$ (D:\Book_Store_App\Book-Store\src\middlewares\/checkuser.middleware.js:16:10)
    at tryCatch (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) 
    url - /api/v1/users/login_user 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-25T08:48:45.779Z"}
error: 
    status - 500 
    message - Error: Please enter correct details
    at _callee$ (D:\Book_Store_App\Book-Store\src\middlewares\/checkuser.middleware.js:16:10)
    at tryCatch (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) 
    url - /api/v1/users/login_user 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-25T08:48:48.537Z"}
error: 
    status - 500 
    message - TypeError: UserService.logiforgetPasswordn is not a function
    at _callee3$ (D:\Book_Store_App\Book-Store\src\controllers\/user.controller.js:41:36)
    at tryCatch (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at forgetPassword (D:\Book_Store_App\Book-Store\src\controllers\/user.controller.js:39:28) 
    url - /api/v1/users/forgetpassword 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-25T09:53:50.427Z"}
error: 
    status - 500 
    message - Error: Mail id does not exsist
    at _callee3$ (D:\Book_Store_App\Book-Store\src\services\/user.service.js:81:11)
    at tryCatch (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) 
    url - /api/v1/users/forgetpassword 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-25T09:55:09.127Z"}
error: 
    status - 500 
    message - ReferenceError: req is not defined
    at _callee4$ (D:\Book_Store_App\Book-Store\src\services\/user.service.js:90:9)
    at tryCatch (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.resetPassword (D:\Book_Store_App\Book-Store\src\services\/user.service.js:89:27) 
    url - /api/v1/users/resetpassword 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-25T12:00:34.654Z"}
error: 
    status - 500 
    message - ReferenceError: decodedToken is not defined
    at _callee4$ (D:\Book_Store_App\Book-Store\src\services\/user.service.js:94:17)
    at tryCatch (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.resetPassword (D:\Book_Store_App\Book-Store\src\services\/user.service.js:89:27) 
    url - /api/v1/users/resetpassword 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-25T12:03:36.234Z"}
error: 
    status - 500 
    message - JsonWebTokenError: invalid token
    at Object.verify (D:\Book_Store_App\Book-Store\node_modules\jsonwebtoken\verify.js:75:17)
    at _callee4$ (D:\Book_Store_App\Book-Store\src\services\/user.service.js:91:27)
    at tryCatch (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12) 
    url - /api/v1/users/resetpassword 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-25T12:16:20.189Z"}
error: 
    status - 500 
    message - Error: data and salt arguments required
    at Object.hash (D:\Book_Store_App\Book-Store\node_modules\bcrypt\bcrypt.js:137:17)
    at D:\Book_Store_App\Book-Store\node_modules\bcrypt\promises.js:29:12
    at new Promise (<anonymous>)
    at Object.module.exports.promise (D:\Book_Store_App\Book-Store\node_modules\bcrypt\promises.js:20:12)
    at Object.hash (D:\Book_Store_App\Book-Store\node_modules\bcrypt\bcrypt.js:133:25)
    at _callee4$ (D:\Book_Store_App\Book-Store\src\services\/user.service.js:99:44)
    at tryCatch (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:294:22) 
    url - /api/v1/users/resetpassword 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-25T12:22:09.644Z"}
error: 
    status - 500 
    message - TypeError: Cannot read property 'split' of undefined
    at _callee4$ (D:\Book_Store_App\Book-Store\src\services\/user.service.js:90:22)
    at tryCatch (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.resetPassword (D:\Book_Store_App\Book-Store\src\services\/user.service.js:89:27) 
    url - /api/v1/users/resetpassword 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-25T12:23:17.262Z"}
error: 
    status - 500 
    message - TypeError: Cannot read property 'split' of undefined
    at _callee4$ (D:\Book_Store_App\Book-Store\src\services\/user.service.js:90:22)
    at tryCatch (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.resetPassword (D:\Book_Store_App\Book-Store\src\services\/user.service.js:89:27) 
    url - /api/v1/users/resetpassword 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-25T12:23:35.767Z"}
error: 
    status - 500 
    message - TypeError: Cannot read property 'split' of undefined
    at _callee4$ (D:\Book_Store_App\Book-Store\src\services\/user.service.js:90:22)
    at tryCatch (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.resetPassword (D:\Book_Store_App\Book-Store\src\services\/user.service.js:89:27) 
    url - /api/v1/users/resetpassword 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-25T12:26:38.102Z"}
error: 
    status - 500 
    message - TypeError: Cannot read property 'split' of undefined
    at _callee4$ (D:\Book_Store_App\Book-Store\src\services\/user.service.js:95:22)
    at tryCatch (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.resetPassword (D:\Book_Store_App\Book-Store\src\services\/user.service.js:89:27) 
    url - /api/v1/users/resetpassword 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-25T12:30:08.867Z"}
error: 
    status - 500 
    message - TypeError: Cannot read property 'split' of undefined
    at _callee4$ (D:\Book_Store_App\Book-Store\src\services\/user.service.js:91:22)
    at tryCatch (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.resetPassword (D:\Book_Store_App\Book-Store\src\services\/user.service.js:89:27) 
    url - /api/v1/users/resetpassword 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-25T12:30:59.288Z"}
error: 
    status - 500 
    message - TypeError: Cannot read property 'split' of undefined
    at _callee4$ (D:\Book_Store_App\Book-Store\src\services\/user.service.js:92:22)
    at tryCatch (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.resetPassword (D:\Book_Store_App\Book-Store\src\services\/user.service.js:89:27) 
    url - /api/v1/users/resetpassword 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-25T12:31:41.358Z"}
error: 
    status - 500 
    message - TypeError: Cannot read property 'split' of undefined
    at _callee4$ (D:\Book_Store_App\Book-Store\src\services\/user.service.js:91:22)
    at tryCatch (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.resetPassword (D:\Book_Store_App\Book-Store\src\services\/user.service.js:89:27) 
    url - /api/v1/users/resetpassword 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-25T12:33:06.751Z"}
error: 
    status - 500 
    message - TypeError: Cannot read property 'split' of undefined
    at _callee4$ (D:\Book_Store_App\Book-Store\src\services\/user.service.js:91:22)
    at tryCatch (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.resetPassword (D:\Book_Store_App\Book-Store\src\services\/user.service.js:89:27) 
    url - /api/v1/users/resetpassword 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-25T12:34:31.245Z"}
error: 
    status - 500 
    message - TypeError: Cannot read property 'split' of undefined
    at _callee4$ (D:\Book_Store_App\Book-Store\src\services\/user.service.js:91:22)
    at tryCatch (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\Book_Store_App\Book-Store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\Book_Store_App\Book-Store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.resetPassword (D:\Book_Store_App\Book-Store\src\services\/user.service.js:89:27) 
    url - /api/v1/users/resetpassword 
    method - POST 
    IP - ::1
   {"timestamp":"2022-01-25T12:34:32.063Z"}
